version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=sushidatabase
      - POSTGRES_PASSWORD=sushidatabase
      - POSTGRES_DB=sushi-prisma
volumes:
  pgdata: